package com.example.alina.todolist.enums;

/**
 * Created by Alina on 07.11.2017.
 */

public enum BundleKey {
    TASK,
    CATEGORY,
    NEED_CHECK_PASSWORD,
    EDIT_MODE,
    CREATE_CATEGORY,
    NAME_TRANSITION,
    DESCRIPTION_TRANSITION,
    CATEGORY_TRANSITION,
    LATITUDE_TRANSITION,
    LOGITUDE_TRANSITION,
    CATEGORY_ID,
    MODE,
    INDEX,
    USER,
    CURRENT_USER,
    TASK_STATUS,
    CURRENT_LOCATION,
    CURRENT_TASK_FOR_MAP,
}
